version: "3.9"


networks:
  net-straight-flush:
    name: straight-flush-net


services:
  app:
    container_name: straight-flush-server
    image: node:16.16.0
    restart: always
    ports:
      - "80:${PORT}"
    volumes:
      - ./:/app
    env_file:
      - .env
    working_dir: /app
    command: yarn dev
    depends_on:
      - db-primary
      - db-secondary
      - db-arbiter
      - session-broker
    networks:
      net-straight-flush:
        aliases:
          - ${HOST}

  db-primary:
    container_name: straight-flush-database-primary
    build:
      context: ./docker
      dockerfile: Dockerfile.mongo
    restart: always
    environment:
      MONGO_ADMIN_NAME:           admin
      MONGO_ADMIN_PASS:           password
      MONGO_APP_USER_NAME:        straight-flush
      MONGO_APP_USER_PASSWORD:    password
      MONGO_TEST_USER_NAME:       straight-flush-test
      MONGO_TEST_USER_PASSWORD:   password
      MONGO_INITDB_DATABASE:      straight-flush
      MONGO_INITDB_TEST_DATABASE: straight-flush-test
    volumes:
      - dp:/data/db
      - ./docker/mongo/conf/primary.conf:/etc/mongod.conf
      - ./docker/mongo/scripts:/scripts
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    depends_on:
      - db-secondary
      - db-arbiter
    networks:
      net-straight-flush:
        aliases:
          - s1.database.straight-flush.pl

  db-secondary:
    container_name: straight-flush-database-secondary
    build:
      context: ./docker
      dockerfile: Dockerfile.mongo
    restart: always
    volumes:
      - ds:/data/db
      - ./docker/mongo/conf/secondary.conf:/etc/mongod.conf
    networks:
      net-straight-flush:
        aliases:
          - s2.database.straight-flush.pl

  db-arbiter:
    container_name: straight-flush-database-arbiter
    build:
      context: ./docker
      dockerfile: Dockerfile.mongo
    restart: always
    volumes:
      - ./docker/mongo/conf/arbiter.conf:/etc/mongod.conf
    networks:
      net-straight-flush:
        aliases:
          - sa.database.straight-flush.pl

  db-admin:
    container_name: straight-flush-admin
    image: mongo-express
    restart: always
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_URL: mongodb://straight-flush:password@s1.database.straight-flush.pl:27017,s2.database.straight-flush.pl:27017,sa.database.straight-flush.pl:27017/straight-flush?ssl=false&replicaSet=rsStraightFlush
    command: node --unhandled-rejections=strict app
    depends_on:
      - db-primary
      - db-secondary
      - db-arbiter
    networks:
      - net-straight-flush

  session-broker:
    container_name: straight-flush-session-broker
    build:
      context: ./docker
      dockerfile: Dockerfile.redis
    restart: always
    volumes:
      - sb:/data
    networks:
      net-straight-flush:
        aliases:
          - session.straight-flush.pl


volumes:
  dp:
    name: straight-flush-data-primary
  ds:
    name: straight-flush-data-secondary
  sb:
    name: straight-flush-session-broker